<?php
/**
 * @file
 * Code for the GSB Feature Mega Menu feature.
 */

include_once 'gsb_feature_mega_menu.features.inc';

/**
 * Implements hook_menu_minipanels_styles().
 */
function gsb_feature_mega_menu_menu_minipanels_styles() {
  $styles = array(
    'megamenu' => t('Mega menu'),
  );
  return $styles;
}

/**
 * Implements hook_menu_minipanels_style().
 */
function gsb_feature_mega_menu_menu_minipanels_style($menu_config) {
  // Load the custom styles in the footer but after other things have loaded.
  drupal_add_js(drupal_get_path('module', 'gsb_feature_mega_menu') . '/js/megamenu_styles.js', array('scope' => 'footer', 'weight' => 100));
  drupal_add_css(drupal_get_path('module', 'gsb_feature_mega_menu') . '/css/megamenu_styles.css');
}

/**
 * Implements hook_entity_info_alter().
 */
function gsb_feature_mega_menu_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['gsb_featured_item'] = array(
    'label' => t('Add GSB Featured Item'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_content_list.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 10,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/gsb-featured-item',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}